apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.varName }}
spec:
  selector:
    matchLabels:
      app: xxx
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
      - name: xxx
        image: xxx
        ports:
        - containerPort: xxx